### ISSUE TITLE
Root is not required to unmount

### ISSUE THREAD

**Issue by Lonami** [spion/adbfs-rootless#26]
This application claims to be rootless, yet it suggests to use `sudo umount` in the `README` which needs root access :P

I haven't tried (but have plans to use) this yet, but I think using `fusermount -u <dir>` should work. Just in case anyone finds this information useful.

**Edit**: Yep, not required, just tested.

**Comment by spion** [comment]
Rootless in this context means you don't have to "root" your phone.

**Comment by Lonami** [comment]
I know, I know. I'm just stating that you don't even need root in the desktop environment to unmount it.

**Comment by Aire-One** [comment]
If I correctly recall, you don't even need root permission (for `mount` and `umount` (desktop side)) with correct rights as a regular user on the mount point...

The problem here is that not everyone can/want to root his Android device.
This repo aims to provide rootless _Android side_ access to the Android device filesystem. The desktop side entirely depends on your local configurations and the way you manage your users rights. 

That said, I'm agreeing with @Lonami. Because adbfs works with FUSE, `fusermount -u` should be used in the README instead of `umount`. At least, it should be mention as an option.

**Comment by spion** [comment]
PR welcome.

**Comment by spion** [comment]
This is all good now I think - closing, but feel free to shout if there are troubles.
